// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./components/layout/header.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpBell: typeof import('~icons/ep/bell')['default']
    IEpBottom: typeof import('~icons/ep/bottom')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpLollipop: typeof import('~icons/ep/lollipop')['default']
    IEpUnfold: typeof import('~icons/ep/unfold')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    Menu: typeof import('./components/layout/menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
